---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webtop
  namespace: testing
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: lscr.io/linuxserver/webtop
      tag: ubuntu-xfce

    service:
      main:
        ports:
          http:
            port: 3000

    env:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver

    persistence:
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: synology-csi-delete

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: "webtop.spenceops.com"
            paths:
              - path: /