---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.yaml
