---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postprocess
  labels:
    type: postprocess
spec:
  capacity:
    storage: 65Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.11
    path: "/volume1/media/postprocess"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postprocess
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 65Ti
  selector:
    matchLabels:
      type: postprocess
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-dev
  labels:
    type: plex-dev
spec:
  capacity:
    storage: 65Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/volume1/plex-dev"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 65Ti
  selector:
    matchLabels:
      type: plex-dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  labels:
    type: downloads
spec:
  capacity:
    storage: 65Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.11
    path: "/volume1/temp/downloads"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 65Ti
  selector:
    matchLabels:
      type: downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
  labels:
    type: downloads
spec:
  capacity:
    storage: 65Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.11
    path: "/volume1/media/tv"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tv
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 65Ti
  selector:
    matchLabels:
      type: tv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
  labels:
    type: movies
spec:
  capacity:
    storage: 65Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.11
    path: "/volume1/media/movies"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: movies
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 65Ti
  selector:
    matchLabels:
      type: movies
---