---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-plex-dev
  labels:
    type: media-plex-dev
spec:
  capacity:
    storage: 65Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/volume1/plex-dev"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-plex-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 65Ti
  selector:
    matchLabels:
      type: media-plex-dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv
  labels:
    type: media-tv
spec:
  capacity:
    storage: 65Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.11
    path: "/volume1/media/tv"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-tv
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 65Ti
  selector:
    matchLabels:
      type: media-tv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies
  labels:
    type: media-movies
spec:
  capacity:
    storage: 65Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.11
    path: "/volume1/media/movies"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-movies
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 65Ti
  selector:
    matchLabels:
      type: media-movies
---