---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.700@sha256:9ae40655d519479d4d70a8d67f929142a0fc2d10df0b75a0947ee3a6c8da7f53

    podSecurityContext:
      runAsUser: 1027
      runAsGroup: 1027
      fsGroup: 1027
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65536

    env:
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: "sonarr.spenceops.com"
            paths:
              - path: /
      external:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: security-middleware-authentik@kubernetescrd
        hosts:
          - host: "sonarr.spenceops.com"
            paths:
              - path: /
        tls:
          - hosts:
            - sonarr.spenceops.com

    persistence:
      postprocess:
        enabled: true
        type: pvc
        mountPath: /postprocess
        existingClaim: downloads-postprocess
      movies:
        enabled: true
        type: pvc
        mountPath: /tv
        existingClaim: downloads-tv
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: synology-csi-retain
        retain: true   

#    resources:
#      requests:
#        cpu: 20m
#        memory: 323M
#      limits:
#        memory: 323M