---
image:
  repository: linuxserver/sabnzbd
  pullPolicy: IfNotPresent
  tag: latest

  strategy:
    type: Recreate

  env:
    TZ: "America/Denver"
    PUID: 
    PGID:


  service:
    main:
      ports:
        http:
          port: 8080
        
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: sabnzbd.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
              service:
                
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 25Gi
      mountPath: /config