---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: plexinc/pms-docker
      tag: latest

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        loadBalancerIP: 10.0.1.200
        ports:
          http:
            port: 32400

    env:
      PLEX_CLAIM: claim-GqNymXW5bp8r6ZptYuxt

    persistence:
      tv:
        enabled: true
        mountPath: /tv
        type: pvc
        existingClaim: media-tv
      movies:
        enabled: true
        mountPath: /movies
        type: pvc
        existingClaim: media-movies
      config:
        enabled: true
        mountPath: /config
        type: pvc
        existingClaim: media-plex
      transcode:
        enabled: true
        type: emptyDir

    #podSecurityContext:
    #  runAsUser: 1027
    #  runAsGroup: 65536
    #  fsGroup: 1027
    #  fsGroupChangePolicy: "OnRootMismatch"
    #  supplementalGroups:
    #    - 44
    #    - 109

    nodeSelector:
      plex: "true"