---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.33.2

    podSecurityContext:
      runAsUser: 1027
      runAsGroup: 1027
      fsGroup: 1027
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65536

    env:
      TZ: America/Denver
      OVERSEERR__PORT: &port 5055

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: "overseerr.spenceops.com"
            paths:
              - path: /
      external:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: security-middleware-authentik@kubernetescrd
        hosts:
          - host: "overseerr.spenceops.com"
            paths:
              - path: /
        tls:
          - hosts:
            - overseerr.spenceops.com

    persistence:
      config:
        enabled: true
        mountPath: /app/config
        existingClaim: downloads-overseerr
        type: pvc
        
#    resources:
#      requests:
#        cpu: 20m
#        memory: 323M
#      limits:
#        memory: 323M