---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/cluster/
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      singlesubtest: "testing"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets