---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    kustomize.toolkit.fluxcd.io/substitute: disabled
  name: nfs-delete
parameters:
  archiveOnDelete: "false"
  pathPattern: ${.PVC.namespace}/${.PVC.name}
provisioner: cluster.local/nfs-subdir-provisioner-nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-subdir-external-provisioner
    kustomize.toolkit.fluxcd.io/substitute: disabled
  name: nfs-retain
parameters:
  archiveOnDelete: "true"
  pathPattern: ${.PVC.namespace}/${.PVC.name}
provisioner: cluster.local/nfs-subdir-provisioner-nfs-subdir-external-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
