---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - storagevolumes/deployment.yaml
  - plex/deployment.yaml
  - tautulli/deployment.yaml
  - plex-dev/deployment.yaml