---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-configs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/cluster-configs/
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  decryption:
    provider: sops
    secretRef:
      name: sops-age