---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  path: ./kubernetes/kube-system/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m