---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfs-subdir-provisioner
  namespace: flux-system
spec:
  dependsOn:
    - name: dolos-cluster
  path: ./kubernetes/cluster/storage/nfs-subdir-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nfs-subdir-provisioner
      namespace: storage
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfs-subdir-provisioner-classes
  namespace: flux-system
spec:
  dependsOn:
    - name: nfs-subdir-provisioner
  path: ./kubernetes/cluster/storage/nfs-subdir-provisioner/storage-classes
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  interval: 30m
  retryInterval: 1m
  timeout: 3m
