---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-storage
  namespace: flux-system
spec:
  dependsOn:
    - name: nfs-subdir-provisioner
  path: ./kubernetes/cluster/monitoring/kube-prometheus/storage/
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-storage
  path: ./kubernetes/cluster/monitoring/kube-prometheus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kube-prometheus
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m