---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.0.2@sha256:0e62d048aa0baba4bd7d2f897a2d3618bbd2ffe8616ef728bf751af999c78537

    podSecurityContext:
      runAsUser: 1027
      runAsGroup: 1027
      fsGroup: 1027
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65536

    env:
      SABNZBD__PORT: &port 8080
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.downloads,
        sabnzbd.downloads.svc,
        sabnzbd.downloads.svc.cluster,
        sabnzbd.downloads.svc.cluster.local,
        sabnzbd.spenceops.com

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: "sabnzbd.spenceops.com"
            paths:
              - path: /
        
    persistence:
      downloads:
        enabled: true
        type: pvc
        mountPath: /downloads
        existingClaim: downloads
      postprocess:
        enabled: true
        type: pvc
        mountPath: /postprocess
        existingClaim: postprocess
      config:
        enabled: false
        type: pvc
        mountPath: /config
        existingClaim: sabnzbd-config
      plex-dev-temp:        
        enabled: true
        type: pvc
        mountPath: /plex-dev-temp
        existingClaim: plex-dev-temp

    #resources:
    #  requests:
    #    cpu: 5m
    #    memory: "2392M"
    #  limits:
    #    memory: "2392M"