controller:
  type: statefulset
  annotations:
    reloader.stakater.com/auto: "true"

image:
  repository: ghcr.io/onedr0p/sabnzbd
  tag: 4.0.2@sha256:0e62d048aa0baba4bd7d2f897a2d3618bbd2ffe8616ef728bf751af999c78537

podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups:
    - 65539

env:
  SABNZBD__PORT: 8080
  SABNZBD__HOST_WHITELIST_ENTRIES: >-
    sabnzbd,
    sabnzbd.downloads,
    sabnzbd.downloads.svc,
    sabnzbd.downloads.svc.cluster,
    sabnzbd.downloads.svc.cluster.local,
    sabnzbd.bjw-s.dev
  #SABNZBD__API_KEY:
  #  valueFrom:
  #    secretKeyRef:
  #      name: sabnzbd-secret
  #      key: api_key
  #SABNZBD__NZB_KEY:
  #  valueFrom:
  #    secretKeyRef:
  #      name: sabnzbd-secret
  #      key: nzb_key

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: "sabnzbd.${SECRET_DOMAIN}"
        paths:
          - path: /
  
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 1Gi
      
resources:
  requests:
    cpu: 5m
    memory: "2392M"
  limits:
    memory: "2392M"

volumeClaimTemplates:
  - name: config
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: nfs-retain