apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-prometheus-prometheus
  labels:
    app.kubernetes.io/name: kube-prometheus-prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.default-target.9ae28f60be2
     lun: 43
     fsType: 'ext4'