kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-prometheus-prometheus
spec:
  storageClassName: nfs-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-prometheus-grafana
spec:
  storageClassName: nfs-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi