---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: storage
spec:
  interval: 5m
  releaseName: synology-csi
  chart:
    spec:
      chart: synology-csi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: synology-csi-values
