---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synology-csi-config
  namespace: flux-system
spec:
  path: ./kubernetes/storage/synology-csi/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  dependsOn:
    - name: synology-csi-config
  path: ./kubernetes/storage/synology-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: synology-csi
      namespace: storage
  interval: 30m
  retryInterval: 1m
  timeout: 3m
