---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synology-csi-config
  namespace: flux-system
spec:
  dependsOn:
    - name: dolos-cluster
  path: ./kubernetes/cluster/storage/synology-csi/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  dependsOn:
    - name: synology-csi-config
  path: ./kubernetes/cluster/storage/synology-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: synology-csi
      namespace: storage
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
