---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfs-subdir-provisioner
  namespace: flux-system
spec:
  path: ./kubernetes/storage/nfs-subdir-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfs-subdir-provisioner-classes
  namespace: flux-system
  kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  dependsOn:
    - name: nfs-subdir-provisioner
  path: ./kubernetes/storage/nfs-subdir-provisioner/storage-classes
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  interval: 30m
  retryInterval: 1m
  timeout: 3m
