---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-certificates
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    resources:
      - apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: "${SECRET_DOMAIN/./-}"
          namespace: security
        spec:
          secretName: "${SECRET_DOMAIN/./-}-tls"
          secretTemplate:
            annotations:
              reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
              reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
              reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "media, traefik, downloads, flux-system, management, monitoring, networking, security, storage"
              reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media, traefik, downloads, flux-system, management, monitoring, networking, security, storage"
          issuerRef:
            name: letsencrypt-production
            kind: ClusterIssuer
          commonName: "${SECRET_DOMAIN}"
          dnsNames:
            - "${SECRET_DOMAIN}"
            - "*.${SECRET_DOMAIN}"