apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: networking

spec:
  defaultGeneratedCert:
    resolver: letsencrypt-production
    domain:
      main: spenceops.com
      sans:
        - "*.spenceops.com"