---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-default-cert
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    resources:
      - apiVersion: traefik.containo.us/v1alpha1
        kind: TLSStore
        metadata:
          name: "spenceops-wildcard"
          namespace: networking
        spec:
          defaultCertificate:
            secretName: "spenceops-tls"