---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Denver"
  METALLB_LB_RANGE: "10.0.1.100-10.0.1.250"
  TRAEFIK_INGRESS_ADDR: "10.0.1.100"