---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 5.1.1.8195@sha256:9579f7c96c5db2f1f98219e83a296b27c696d1f7e18ab4cf2deb90e9e9b3ef37

    podSecurityContext:
      runAsUser: 1027
      runAsGroup: 1027
      fsGroup: 1027
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65536

    env:
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 7878
      
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: "radarr.spenceops.com"
            paths:
              - path: /
      external:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: security-middleware-authentik@kubernetescrd
        hosts:
          - host: "radarr.spenceops.com"
            paths:
              - path: /
        tls:
          - hosts:
            - radarr.spenceops.com
        
    persistence:
      postprocess:
        enabled: true
        type: pvc
        mountPath: /postprocess
        existingClaim: downloads-postprocess
      movies:
        enabled: true
        type: pvc
        mountPath: /movies
        existingClaim: downloads-movies
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: synology-csi-retain
        retain: true   

    #resources:
    #  requests:
    #    cpu: 14m
    #    memory: 431M
    #  limits:
    #    memory: 431M
