---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 4.6.3.7516@sha256:798fe8b616da785edcb84cc871111e63c9227b970dbd33b4ac876faba4c058b8

    podSecurityContext:
      runAsUser: 1027
      runAsGroup: 1027
      fsGroup: 1027
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65536

    env:
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 7878
      RADARR__APPLICATION_URL: "https://radarr.spenceops.com"
      
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: "radarr.spenceops.com"
            paths:
              - path: /
        
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config

      media:
        enabled: true
        type: nfs
        server: "nas.bjw-s.tech"
        path: /volume1/Media
        mountPath: /data/nas-media

    #resources:
    #  requests:
    #    cpu: 14m
    #    memory: 431M
    #  limits:
    #    memory: 431M
