---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.12.4@sha256:d4b2306a6c34fdb82e8c1b2a61e71797a201664d7a7b0b602f8a524ef5e2b641

    service:
      main:
        ports:
          http:
            port: 8181

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: tautulli.spenceops.com
            paths:
              - path: /
                pathType: Prefix

    podSecurityContext:
      runAsUser: 1027
      runAsGroup: 65536
      fsGroup: 1027
      fsGroupChangePolicy: "OnRootMismatch"
        
    persistence:
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: synology-csi-retain
        retain: true   