---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.13.1@sha256:525209414d149214584819313b0ec7507a3259dfa5f8d618692c34b54f172db9

    service:
      main:
        ports:
          http:
            port: 8181

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: tautulli.spenceops.com
            paths:
              - path: /
                pathType: Prefix
      external:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: security-middleware-authentik@kubernetescrd
        hosts:
          - host: "tautulli.spenceops.com"
            paths:
              - path: /
        tls:
          - hosts:
            - tautulli.spenceops.com

    podSecurityContext:
      runAsUser: 1027
      runAsGroup: 65536
      fsGroup: 1027
      fsGroupChangePolicy: "OnRootMismatch"
        
    persistence:
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: synology-csi-retain
        retain: true   