---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  path: ./kubernetes/cluster/kube-system/node-feature-discovery/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dolos
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets